name: Debug with the act
on:
  push:
    tags:
      - 'debug*'
jobs:
  dummy:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --root-user-action=ignore PyGithub
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Test case 1 overwrite from custom directory
        uses: dev/github-pages-overwriter@v0
        with:
          source-directory: test
          target-branch: debug
      - name: Check file content using PyGithub
        env:
          GITHUB_TOKEN: ${{ secrets.ACTIONS_PAT }}
        run: |
          python validate.py ${{ github.repository }} debug test
      - name: Test case 1 overwrite from root directory
        uses: dev/github-pages-overwriter@v0
        with:
          source-directory: .
          target-branch: debug
      - name: Check file content using PyGithub
        env:
          GITHUB_TOKEN: ${{ secrets.ACTIONS_PAT }}
        run: |
          python validate.py ${{ github.repository }} debug .
